import { Lab } from "./types"; // Adjust the path as necessary

export const labsData: Lab[] = [
  {
    id: 7,
    name: "Food Bot Jailbreak Tutorial",
    participants: 789,
    gpuRequired: false,
    difficulty: "Medium",
    timeEstimate: "30-60 mins",
    pointsReward: 3500,
    successRate: 42,
    isTutorial: true,
    description: "Learn the basics of AI jailbreaking with this interactive Food Bot tutorial.",
    category: "Jailbreak",
  },
  {
    id: 1,
    name: "GPT-4 Jailbreak",
    participants: 1234,
    gpuRequired: true,
    difficulty: "Hard",
    timeEstimate: "2-3 hours",
    pointsReward: 5000,
    successRate: 68,
    category: "Jailbreak",
  },
  {
    id: 2,
    name: "DALL-E Prompt Optimization",
    participants: 567,
    gpuRequired: false,
    difficulty: "Medium",
    timeEstimate: "1-2 hours",
    pointsReward: 3000,
    successRate: 75,
    category: "Optimization",
  },
  {
    id: 3,
    name: "LLaMA Fine-tuning",
    participants: 890,
    gpuRequired: true,
    difficulty: "Expert",
    timeEstimate: "4-6 hours",
    pointsReward: 8000,
    successRate: 45,
    category: "Fine-tuning",
  },
  {
    id: 4,
    name: "Stable Diffusion Tweaking",
    participants: 2345,
    gpuRequired: true,
    difficulty: "Medium",
    timeEstimate: "2-3 hours",
    pointsReward: 4000,
    successRate: 82,
    category: "Optimization",
  },
  // Add more labs as needed
];